### PR TITLE
SY-1020 Added a Local Cluster to Console

### PR DESCRIPTION
**Pull request by pjdotson**
# Feature Pull Request Template

## Key Information

- **Linear Issue**: [SY-1020](https://linear.app/synnaxlabs/issue/SY-1020/bring-back-local-cluster)

## Description

Automatically connect to cluster running at localhost 9090 on the console.

## Basic Readiness Checklist

- [x] I have performed a self-review of my code.
- [x] I have added relevant tests to cover the changes to CI.
- [x] I have updated user facing documentation accordingly.
- [x] I have verified code coverage targets are met.

## Migrations

- [x] Console - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.
- [x] Server - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.

##  Additional Notes
- [ ] These changes deal with concurrency.
- [x] These changes affect UI.

## Manual QA Additions

- [x] I have updated the [Release Candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template
with necessary manual QA steps to test my change.

## Breaking Changes

Please list any breaking changes to public or internal packages.

## Reviwer Checklist
- [ ] Sufficient test coverage of new additions.
- [x] Verified all steps in the Readiness checklists.
- [x] UI changes have been tested.
- [x] Style and formatting is consistent.
- [ ] Reviewed any relevant changes to concurrent code for safety. 
- [x] Sufficient comments and clarity of code.
- [ ] Any additional documentation necessary for feature is provided and has been reviewed for clarity.

### CODE REVIEW

**Review by Lham42 — APPROVED** [review]
Do we want to check this as a part of the QA process? Otherwise approved

**Review by emilbon99 — APPROVED** [review]
Go through and add a migration.

**Comment by pjdotson** [comment]
> Do we want to check this as a part of the QA process? Otherwise approved

I don't think that's necessary for this PR.

**Review by emilbon99 — APPROVED** [review]
LGTM

**Pull request merged**
