### PR TITLE
HOTFIX - SY-1057 revert access control setting

### PR DESCRIPTION
**Pull request by Lham42**
# Fix Pull Request Template

## Key Information

- **Linear Issue**: [SY-1057]()

## Description

This changes user access config so that there is no restrictions. This is to address the issue of migrating over existing user information for the root user (where it is not given any access). This branches off of [PR 763](https://github.com/synnaxlabs/synnax/pull/763) as otherwise the issue could not be replicated. only merge this in once that one has been merged and rc/main has been backmerged in.

## Basic Readiness Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added sufficient regression tests to cover the changes to CI.
- [ ] I have added relevant tests to cover the changes or exposing bugs.
- [x] I have verified code coverage targets are met.

## Additional Notes
- [ ] These changes deal with concurrency.
- [ ] These changes affect UI.

## Manual QA Additions

- [ ] I have updated the [Release Candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template
  with necessary manual QA steps to test my change.

## Reviewer Checklist
- [ ] Sufficient test coverage of new additions.
- [ ] Verified all steps in readiness checklists.
- [ ] UI changes have been tested.
- [ ] style and formatting is consistent.
- [ ] Reviewed any relevant changes to concurrent code for safety. 
- [ ] Sufficient comments and clarity of code.

### CODE REVIEW

**Comment by Lham42** [comment]
Currently having the setting access to Allow all will cause tests in ts and py classes to fail which intentionally try to raise a auth error. Should we comment these tests out now?

**Review by emilbon99 — APPROVED** [review]
LGTM

**Review by emilbon99 — CHANGES_REQUESTED** [review]
Client TS and PY tests are failing

**Review by emilbon99 — APPROVED** [review]
LGTM

**Pull request merged**
