### PR TITLE
459 queue

### PR DESCRIPTION
**Pull request by t1an-xyz**
Implement a deque

Modify stack and queue to use a deque as the underlying container

Modify `Peek()` in stack and queue to return a copy rather than a pointer

Modify calc to accommodate for the previous change

### CODE REVIEW

**Comment by emilbon99** [comment]
If stack and queue are just using a deque under the hood, then why are we defining them as concrete types? Can't we just (1) use a deque for everything instead or (2) have the stack and queue defined as interfaces that the deque implements?

**Review by emilbon99 — COMMENTED** [review]
See my comment

**Comment by t1an-xyz** [comment]
> If stack and queue are just using a deque under the hood, then why are we defining them as concrete types? Can't we just (1) use a deque for everything instead or (2) have the stack and queue defined as interfaces that the deque implements?

I mostly did that for backwards compatibility since I thought it was bad practice to remove code in case some older code relies on it. I have replaced the stack used in the calc library with a deque.

**Comment by emilbon99** [comment]
Fantastic! This looks great

**Pull request merged**
