### PR TITLE
SY-1096 Update Client API GitHub Action to Pass on Back Merges

### PR DESCRIPTION
**Pull request by pjdotson**
This PR changes the client API GitHub action to pass when there are API changes in the base branch.

### CODE REVIEW

**Comment by Lham42** [comment]
So to clarify - will the check pass only once we backmerge the base branch which has API changes?

**Review by Lham42 — CHANGES_REQUESTED** [review]
Can you give an example of the process that would happen now with the change to the workflow because it is not immediately clear to me now. Does this workflow now automatically backmerge the base branch  for an open pr too?

**Comment by pjdotson** [comment]
Steps:
1. Checks for diffs in any package that could cause an API change (x, alamos, freighter, client)
2. Checks out the repo
3. Fetches the base branch (if PR is for merging into rc, it fetches rc).
4. On the local repo, merges the base branch (eg rc) into the head branch (the hash that the PR is opened on).
5. checks if the API has changed on the local repo, compared to the existing `client.api.md` document. If so, this workflow fails, if not, the workflow passes.

It does not affect the code on the remote branches because it never pushes code to the repo. It doesn't automatically backmerge the base branch for an open PR.

**Review by Lham42 — APPROVED** [review]
LGTM

**Pull request merged**
