### PR TITLE
SY-1098 Add Ability to Resize Most Schematic Symbols

### PR DESCRIPTION
**Pull request by pjdotson**
# Feature Pull Request Template

## Key Information

- **Linear Issue**: [SY-1098](https://linear.app/synnax/issue/SY-1098/add-ability-to-resize-any-schematic-symbol)

## Description

Added ability to resize (almost) any schematic symbols - buttons, switches, values, and setpoints still cannot be resized. Also refactored some code in relevant files.

NOTE: Previous versions of the schematic will have a `scale` of `null`, so the options for scaling them will not show up. I don't know a great way to fix this problem, and don't think it matters too much - all it means is that the elements created before this version gets released cannot be scaled. If someone wants to scale that element, they could delete it and replace it with a new one.

## Basic Readiness Checklist

- [x] I have performed a self-review of my code.
- [x] I have added relevant tests to cover the changes to CI.
- [x] I have updated user facing documentation accordingly.
- [x] I have verified code coverage targets are met.

## Migrations

- [ ] Console - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.
- [ ] Server - I have ensured that previous versions of stored data structures are 
properly migrated to new formats.

##  Additional Notes
- [ ] These changes deal with concurrency.
- [ ] These changes affect UI.

## Manual QA Additions

- [ ] I have updated the [Release Candidate](/.github/PULL_REQUEST_TEMPLATE/rc.md) template
with necessary manual QA steps to test my change.

## Breaking Changes

Please list any breaking changes to public or internal packages.

## Reviwer Checklist
- [ ] Sufficient test coverage of new additions.
- [ ] Verified all steps in the Readiness checklists.
- [ ] UI changes have been tested.
- [ ] Style and formatting is consistent.
- [ ] Reviewed any relevant changes to concurrent code for safety. 
- [ ] Sufficient comments and clarity of code.
- [ ] Any additional documentation necessary for feature is provided and has been reviewed for clarity.

### CODE REVIEW

**Comment by pjdotson** [comment]
Leaving a comment here - I need to check how migrating old symbols into this works. I believe what will happen is that the scale will not show up on the form because it is null for old symbols.

**Comment by emilbon99** [comment]
This generally looks ok. I think we need to make some other changes for this feature to be nice though. Label positions look strange when elements are larger. Take this rotary mixer for example. It's probably pretty common to want to make this thing pretty large. It looks strange to fill in the entire mixer when it is turned on. We should probably make it so you hook up a switch to turn the mixer on and off, then we can make it possible to hide and show the controls states on it, so then it becomes more of a 'static' element.

Also, if you can scale the element, you should also have the option to make the stroke width of the symbol larger or smaller.

Screenshot 2024-09-07 at 8 16 08 PM

**Comment by emilbon99** [comment]
Screenshot 2024-09-07 at 8 17 52 PM

Just looks kinda strange to have this massive, white rotary mixer on the screen

**Comment by emilbon99** [comment]
Even though you would probably want to have a rotary mixer that big on your P&ID

**Review by emilbon99 — APPROVED** [review]
Approved, although I think we need to spend more time thinking about the larger implications of making sure this feature has a nice UX

**Pull request merged**
