### PR TITLE
Ebonilla/sy 719 channel renaming

### PR DESCRIPTION
**Pull request by emilbon99**

### CODE REVIEW

**Comment by pjdotson** [comment]
I got this error here when trying to rename on the console: 
Screenshot 2024-06-03 at 10 13 50 AM

**Comment by emilbon99** [comment]
Did you rebuild pluto?

**Comment by LeonLiur** [comment]
> I got this error here when trying to rename on the console: Screenshot 2024-06-03 at 10 13 50 AM

did Patrick get a Mac ?!

**Comment by emilbon99** [comment]
Yessir

**Pull request merged**
